[package]
name = "huxplex"
version = "0.1.0"
edition = "2024"

[dependencies]
libcrux-ml-dsa = "0.0.7"
libcrux-ml-kem = "0.0.7"
hkdf = "0.12.4"
sha2 = "0.10.9"
sha3 = "0.10.8"
thiserror = "2.0.18"
hex = "0.4.3"
bip32 = "0.5.3"
rand = "0.10.0"
